api-key = ""
model = "gpt-3.5-turbo"
vi_mode = false
visible_overflow = true
# Default one used by OpenAI. If you don't want it you can comment it out.
context = "You are ChatGPT, a large language model trained by OpenAI. Answer as concisely as possible."
